export const LOAD_ALL_PROGRAMS = "LOAD_ALL_PROGRAMS";
export const SEARCH_PROGRAM = "SEARCH_PROGRAM";

export const LOAD_ALL_STUDENTS = "LOAD_ALL_STUDENTS";
export const SEARCH_STUDENT = "SEARCH_STUDENT";

