export const LOAD_ALL_PROGRAMS = "LOAD_ALL_PROGRAMS";
export const SEARCH_PROGRAM = "SEARCH_PROGRAM";
export const LOAD_ONE_PROGRAM = "LOAD_ONE_PROGRAM";

export const LOAD_ALL_STUDENTS = "LOAD_ALL_STUDENTS";
export const SEARCH_STUDENT = "SEARCH_STUDENT";
export const LOAD_ONE_STUDENT = "LOAD_ONE_STUDENT";

export const LOAD_ALL_APPLICATIONS = "LOAD_ALL_APPLICATIONS";
export const LOAD_ONE_APPLICATION = "LOAD_ONE_APPLICATION";
export const SEARCH_APPLICATION = "SEARCH_APPLICATION";

